#  ▀█████████▄     ▄████████    ▄████████    ▄████████    ▄████████ ███▄▄▄▄       ███      ▄█     ▄████████  ▄█          ▄████████
#    ███    ███   ███    ███   ███    ███   ███    ███   ███    ███ ███▀▀▀██▄ ▀█████████▄ ███    ███    ███ ███         ███    ███
#    ███    ███   ███    █▀    ███    █▀    ███    █▀    ███    █▀  ███   ███    ▀███▀▀██ ███▌   ███    ███ ███         ███    █▀
#   ▄███▄▄▄██▀   ▄███▄▄▄       ███          ███         ▄███▄▄▄     ███   ███     ███   ▀ ███▌   ███    ███ ███         ███
#  ▀▀███▀▀▀██▄  ▀▀███▀▀▀     ▀███████████ ▀███████████ ▀▀███▀▀▀     ███   ███     ███     ███▌ ▀███████████ ███       ▀███████████
#    ███    ██▄   ███    █▄           ███          ███   ███    █▄  ███   ███     ███     ███    ███    ███ ███                ███
#    ███    ███   ███    ███    ▄█    ███    ▄█    ███   ███    ███ ███   ███     ███     ███    ███    ███ ███▌    ▄    ▄█    ███
#  ▄█████████▀    ██████████  ▄████████▀   ▄████████▀    ██████████  ▀█   █▀     ▄████▀   █▀     ███    █▀  █████▄▄██  ▄████████▀
#                                                                                                           ▀

# Restart Server after making any changes or they won't have any effect until you restart.
# Our /bess reload command does not reload this file.
#Practically every feature in this plugin is optional.

config-version: 1

redis:
  host: "localhost"
  port: 6379
  timeout: 5000
  pass: "your_password"

settings:
  announcement-interval: 10 #seconds
  announcement-delay: 1 #ticks
  announcements: true
  join-message: true
  leave-message: true
  help-command: true
  lobby-command: true
  staffchat-command: true
  messagesystem-commands: true
  motd: true
  broadcast-afk: true

  tpa-expiretime: 30 #in seconds
  tpahere-expiretime: 30 #in seconds

lobby:
  lobby-name: "lobby"